version: '3'

networks:
    postgres-net:
        driver: bridge

services:

    postgres:
        container_name: postgres
        image: postgres:${POSTGRES_VERSION}
        restart: unless-stopped
        ports:
            - "5432:5432"
        volumes:
            - ./postgres/master/initdb.d/init-user-db.sql:/docker-entrypoint-initdb.d/init-user-db.sql
            - postgres-master:/var/lib/postgresql/data
        env_file:
            - ./postgres/master/.env.master
        networks:
            - postgres-net

volumes:
    postgres-master:
        driver: local
